### ISSUE TITLE
Review dịch chương Tutorial 1

### ISSUE THREAD

**Issue by phuongnq** [xitrum-framework/xitrum-doc#141]
Khi khởi động, tất cả các định tuyến (routers) sẽ được kiểm tra và lưu vào log. Bạn đã có luôn danh sách các định tuyến (routers), điều này rất thuận tiện với bạn để viết tài liệu về RESTful APIs của ứng dụng web cho bên thứ 3.
===>
"sẽ được kiểm tra và lưu vào log" nên chuyển thành "sẽ được thu thập và xuất ra log".
collect => thu thập, tập hợp
output => xuất dữ liệu ra

**Comment by phuongnq** [comment]
Bạn có thể autoreload các tập tin .class (hot swap) mà không cần phải khởi động lại chương trình. Tuy nhiên, để tránh gặp phải các vấn đề về hiệu suất cũng như tính ổn định của chương trình, bạn chỉ nên autoreload các tập tin .class trong quá trình phát triển (development mode).
====>
"trong quá trình phát triển" nên chuyển thành "trong chế độ phát triển"
mode nghĩa là "chế độ", trong quá trình phát triển cũng có thể sử dụng mode development hoặc mode product

**Comment by phuongnq** [comment]
Một để chạy sbt/sbt run. Câu lệnh này để chạy trương trình và tải lại các tập .class khi chúng được thay đổi.
====> 
"trương trình" => "chương trình"

**Comment by phuongnq** [comment]
Một để chạy sbt/sbt ~compile. Câu lệnh này để biên dịch mã nguồn thành các tập .class.
===>
Câu thứ hai dịch có vẻ không sát câu gốc:
"Mỗi khi bạn thay đổi mã nguồn của tập tip,  câu lệnh này sẽ biên dịch lại mã nguồn thành các tập tin .class"

**Comment by phuongnq** [comment]
file .project cho Eclipse sẽ được tạo với thông tin trong file build.sbt. Sau đó chạy Eclipse và import project.
===>
Đầu câu nên viết hoa: "file" => "File"

**Comment by phuongnq** [comment]
Trong thư mục sbt, có một tập tin agent7.jar. Tập tin này chịu trách nhiệm tải lại các tập .class trong thư mục và các thư mục con. Nếu bạn thấy đoạn script sbt/sbt, bạn sẽ thấy tùy chọn như -javaagent:agent7.jar.
===>
"tải lại các tập .class trong thư mục" => "tải lại các tập tin .class trong thư mục đang làm việc"
"đoạn script" => đoạn mã (nên dùng tiếng Việt nếu có thể)
"see" có thể hiểu là "nhìn vào"
==> "Nếu bạn nhìn vào đoạn mã `sbt/sbt`"

**Comment by phuongnq** [comment]
Thông thường JVM chỉ cho phép thay đổi nội dung của một method. Bạn có thể sử dụng DCEVM, một biến thể mã nguồn mở của máy ảo Java HotSpot VM cho phép bạn thoải mái định nghĩa lại các class đã được tải.
====>
"thoải mái" không phải từ chuyên ngành, nên chuyển lại thành "không hạn chế"

**Comment by phuongnq** [comment]
Bạn có thể chạy DCEVM chạy mãi mãi.
====>
"Bạn có thể khởi động (kích hoạt) DCEVM chạy vĩnh viễn" (mãi mãi cũng không hẳn là từ chuyên ngành)

**Comment by phuongnq** [comment]
Hoặc sử dụng như một JVM khác. Trong trường hợp này, để chạy DCEVM bạn cần chạy câu lệnh java với tùy chọn -XXaltjvm=dcevm. Ví dụ, bạn cần thêm tùy chọn -XXaltjvm=dcevm vào câu lệnh sbt/sbt.
===>
"sử dụng như một JVM khác" => "sử dụng như một JVM thay thế". Alternative nghĩa là thay thế
"để chạy" => "để khởi động", "kích hoạt"

**Comment by phuongnq** [comment]
Nếu bạn sử dụng SBT, bạn cần cài đặt biến môi trường PATH với đường dẫn câu lệnh java từ DCEVM (không phải bản JVM mặc định). Bạn vẫn có thể cần đến javaagent trên đây, bởi vì mặc dù DCEVM hỗ trợ các tiện ích khi sửa đổi các class, nó không thể tự tải lại các class.
=======>
"với đường dẫn câu lệnh java.." => "để câu lệnh `java` có đường dẫn từ DCEVM (mà không phải từ bản JVM mặc định)".
"so that" nghĩa là "để", "để cho"

**Comment by phuongnq** [comment]
@ngocdaothanh please review my review if needed!

**Comment by ngocdaothanh** [comment]
Cảm ơn Phương.

Chỗ "thoải mái" anh nghĩ cũng có thể thoải mái chỗ này. Từ này cũng thoát ý, dễ hiểu.

> You can enable DCEVM permanently.

"permanently" có vẻ hơi khó dịch thoát ý. Câu này có thể dịch k sát từng chữ word by word, mà dịch theo kiểu diễn giải cho dễ hiểu, ví dụ: Bạn có thể thiết lập để luôn luôn dùng DCEVM để chạy chương trình, lúc chạy không cần chỉ định tham số gì thêm.

**Comment by phuongnq** [comment]
@ngocdaothanh ok anh ạ.
Ở trên là em review theo góc nhìn của em. anh Ngọc hoặc @wingadium1  thấy chỗ nào không hợp lý thì cứ thay đổi cho hợp lý nhé!

**Comment by ngocdaothanh** [comment]
Cảm ơn Phương.
Anh em đang hóng Phương viết review cho những chương tiếp theo :dancers:
